In [104]:
%pylab inline
numpy.set_printoptions(precision=2,suppress=True)

Populating the interactive namespace from numpy and matplotlib


In [143]:
A = zeros((10,10))
for i in range(10):
    A[i,i]=i+1
for i in range(9):    
    A[i,i+1]=11+i
for i in range(9):    
    A[i+1,i]=102+i

In [144]:
A

array([[  1.,  11.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [102.,   2.,  12.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0., 103.,   3.,  13.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0., 104.,   4.,  14.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0., 105.,   5.,  15.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0., 106.,   6.,  16.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0., 107.,   7.,  17.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0., 108.,   8.,  18.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0., 109.,   9.,  19.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., 110.,  10.]])

In [145]:
a=diag(A)
b=diag(A,-1)
c=diag(A,+1)

alfa=zeros(10)
beta=zeros(9)

In [146]:
a,b,c

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 array([102., 103., 104., 105., 106., 107., 108., 109., 110.]),
 array([11., 12., 13., 14., 15., 16., 17., 18., 19.]))

In [172]:
alfa[0]=a[0]
for i in range(1,9):
    beta[i-1]=b[i-1]/alfa[i-1]
    alfa[i]=a[i]-beta[i-1]*c[i-1]
alfa, beta

(array([    1.  , -1120.  ,     4.1 ,  -325.47,     9.52,  -161.08,
           17.63,   -96.15,    29.41,     0.  ]),
 array([102.  ,  -0.09,  25.34,  -0.32,  11.14,  -0.66,   6.13,  -1.13,
         -0.05]))

In [173]:
L=zeros((10,10))
U=L

In [174]:
L=diag(ones(10))+diag(beta,-1)
U=diag(alfa)+diag(c,+1)
L,U


(array([[  1.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,
           0.  ,   0.  ],
        [102.  ,   1.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,
           0.  ,   0.  ],
        [  0.  ,  -0.09,   1.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,
           0.  ,   0.  ],
        [  0.  ,   0.  ,  25.34,   1.  ,   0.  ,   0.  ,   0.  ,   0.  ,
           0.  ,   0.  ],
        [  0.  ,   0.  ,   0.  ,  -0.32,   1.  ,   0.  ,   0.  ,   0.  ,
           0.  ,   0.  ],
        [  0.  ,   0.  ,   0.  ,   0.  ,  11.14,   1.  ,   0.  ,   0.  ,
           0.  ,   0.  ],
        [  0.  ,   0.  ,   0.  ,   0.  ,   0.  ,  -0.66,   1.  ,   0.  ,
           0.  ,   0.  ],
        [  0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   6.13,   1.  ,
           0.  ,   0.  ],
        [  0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,  -1.13,
           1.  ,   0.  ],
        [  0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,
          -0.05,   1.  ]]),
 array([

In [175]:
L.dot(U)

array([[  1.  ,  11.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,
          0.  ,   0.  ],
       [102.  ,   2.  ,  12.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,
          0.  ,   0.  ],
       [  0.  , 103.  ,   3.  ,  13.  ,   0.  ,   0.  ,   0.  ,   0.  ,
          0.  ,   0.  ],
       [  0.  ,   0.  , 104.  ,   4.  ,  14.  ,   0.  ,   0.  ,   0.  ,
          0.  ,   0.  ],
       [  0.  ,   0.  ,   0.  , 105.  ,   5.  ,  15.  ,   0.  ,   0.  ,
          0.  ,   0.  ],
       [  0.  ,   0.  ,   0.  ,   0.  , 106.  ,   6.  ,  16.  ,   0.  ,
          0.  ,   0.  ],
       [  0.  ,   0.  ,   0.  ,   0.  ,   0.  , 107.  ,   7.  ,  17.  ,
          0.  ,   0.  ],
       [  0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  , 108.  ,   8.  ,
         18.  ,   0.  ],
       [  0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  , 109.  ,
          9.  ,  19.  ],
       [  0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,
         -1.37,  -0.89]])

In [190]:
y=zeros(10)
bb=A.dot(ones(10))
y[0]=b[0]
for i in range(1,10):
    y[i]=bb[i]-beta[i-1]*y[i-1]
bb, y

(array([ 12., 116., 119., 122., 125., 128., 131., 134., 137., 120.]),
 array([   102.  , -10288.  ,   -827.13,  21084.56,   6927.12, -77029.57,
        -51038.02, 312816.54, 354760.5 ,  16704.72]))

In [188]:
x=zeros(10)
x[9]=y[9]/alfa[9]


/home/marco/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in double_scalars
  


In [ ]:
for i in range (8,0,-1):
    x[i]=(y[i]-c[i]*x[i+1])/alfa[i]
    